apiVersion: v1
kind: ConfigMap
metadata:
  name: spam-classifier-config
  namespace: spam-classifier
data:
  MODEL_VERSION: "v1.0.0"
  MODEL_PATH: "models/model.pkl"
  VECTORIZER_PATH: "models/vectorizer.pkl"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
