apiVersion: v1
kind: Service
metadata:
  name: spam-classifier-service
  namespace: spam-classifier
  labels:
    app: spam-classifier
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8501"
spec:
  type: LoadBalancer
  selector:
    app: spam-classifier
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP
  sessionAffinity: None
